name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Add msbuild to PATH ofcourse
        uses: microsoft/setup-msbuild@v1.1
      - name: Build app for release
        run: msbuild remote_gibme.sln -t:Rebuild -p:Configuration=Release -p:Platform=x86
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Release/remote_gibme.dll
